package buildlocal

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestInstallBuildsUsesConfiguredSDKRoot verifies that local installs honor
// MRS_SDK_QT_ROOT instead of silently writing into the default home-directory
// path. This keeps the install destination aligned with `just install` and the
// project-local wrappers generated by `mrs-sdk-manager use`.
func TestInstallBuildsUsesConfiguredSDKRoot(t *testing.T) {
	repoRoot := t.TempDir()
	homeDir := t.TempDir()
	sdkRoot := filepath.Join(t.TempDir(), "custom-sdk-root")

	t.Setenv("HOME", homeDir)
	t.Setenv("MRS_SDK_QT_ROOT", sdkRoot)

	createFakeSDKRepo(t, repoRoot)

	if err := InstallBuilds(repoRoot); err != nil {
		t.Fatalf("InstallBuilds returned error: %v", err)
	}

	versionRoot := filepath.Join(sdkRoot, "0.0.0")
	assertFileExists(t, filepath.Join(versionRoot, "include", "mrs-sdk-qt", "sdk.hpp"))
	assertFileExists(t, filepath.Join(versionRoot, "lib", "cmake", "mrs-sdk-qt", "config.cmake"))
	assertFileExists(t, filepath.Join(versionRoot, "lib", "qmake", "mrs-sdk-qt", "config.pri"))

	for _, target := range AllBuildTargets() {
		assertFileExists(t, filepath.Join(versionRoot, target.InstTreeDir(), "libmrs-sdk-qt.a"))
	}

	legacyRoot := filepath.Join(homeDir, "mrs-sdk-qt")
	if _, err := os.Stat(legacyRoot); !os.IsNotExist(err) {
		t.Fatalf("expected legacy install root %s to remain unused, stat error: %v", legacyRoot, err)
	}
}

// TestInstallBuildsRequiresSDKRoot verifies that install commands fail fast
// when the configured SDK root is missing instead of guessing a default path.
func TestInstallBuildsRequiresSDKRoot(t *testing.T) {
	t.Setenv("MRS_SDK_QT_ROOT", "")

	err := InstallBuilds(t.TempDir())
	if err == nil {
		t.Fatal("expected InstallBuilds to fail when MRS_SDK_QT_ROOT is unset")
	}
	if !strings.Contains(err.Error(), "MRS_SDK_QT_ROOT is not set") {
		t.Fatalf("expected unset-root error, got %v", err)
	}
}

// createFakeSDKRepo builds the minimal repository layout that InstallBuilds
// expects so the test can validate copy destinations without running the full
// native and cross-compilation toolchains.
func createFakeSDKRepo(t *testing.T, repoRoot string) {
	t.Helper()

	writeTestFile(t, filepath.Join(repoRoot, "lib", "include", "mrs-sdk-qt", "sdk.hpp"), "header")
	writeTestFile(t, filepath.Join(repoRoot, "lib", "cmake", "mrs-sdk-qt", "config.cmake"), "cmake")
	writeTestFile(t, filepath.Join(repoRoot, "lib", "qmake", "mrs-sdk-qt", "config.pri"), "qmake")

	for _, target := range AllBuildTargets() {
		writeTestFile(t, filepath.Join(repoRoot, "build", target.BuildDir(), "artifacts", "libmrs-sdk-qt.a"), target.BuildDir())
	}
}

// writeTestFile creates a file and any missing parent directories so the test
// fixtures stay focused on behavior instead of repetitive setup boilerplate.
func writeTestFile(t *testing.T, path, content string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("failed to create directory for %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("failed to write %s: %v", path, err)
	}
}

// assertFileExists reports a focused failure for missing installed artifacts.
func assertFileExists(t *testing.T, path string) {
	t.Helper()

	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected file %s to exist: %v", path, err)
	}
}
