name: Other
description: Add some other type of issue.
projects: ["mrs-electronics-inc/4"]
assignees:
- bambam955
body:
- type: textarea
  attributes:
    label: Description
    description: A concise description of what needs done.
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposal
    description: The implementation checklist.
  validations:
    required: false
- type: checkboxes
  id: terms
  attributes:
    label: Contributing
    description: By submitting this issue, you agree to follow our [contributor manual](https://github.com/mrs-electronics-inc/mrs-sdk-qt/blob/main/CONTRIBUTING.md).
    options:
      - label: I agree to follow this project's contributor manual
        required: true
