# MRS SDK Qt - Project-local configuration
# Generated by: mrs-sdk-manager use {{.Version}}
#
# This file pins the SDK version for this project.
# Include it in your CMakeLists.txt after setting MRS_SDK_QT_CONSUMER_TARGET.

set(MRS_SDK_QT_ROOT "$ENV{HOME}/mrs-sdk-qt")
set(MRS_SDK_QT_VERSION "{{.Version}}")

# Validate that the SDK version is installed.
set(_mrs_sdk_qt_version_dir "${MRS_SDK_QT_ROOT}/${MRS_SDK_QT_VERSION}")
if(NOT EXISTS "${_mrs_sdk_qt_version_dir}")
    message(FATAL_ERROR "MRS SDK version ${MRS_SDK_QT_VERSION} is not installed. Expected at ${_mrs_sdk_qt_version_dir}")
endif()

# Set the global config file reference for config.cmake validation.
set(_mrs_sdk_qt_global_config_file "${CMAKE_CURRENT_LIST_FILE}")

# Include the SDK configuration.
include("${_mrs_sdk_qt_version_dir}/lib/cmake/mrs-sdk-qt/config.cmake")
