# MRS SDK Qt - Project configuration
# Generated by: mrs-sdk-manager use {{.Version}}
#
# Include this file in your CMakeLists.txt after setting MRS_SDK_QT_CONSUMER_TARGET.

# Read the pinned SDK version.
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/version.conf" _mrs_sdk_qt_version_line REGEX "^MRS_SDK_QT_VERSION=")
string(REGEX REPLACE "^MRS_SDK_QT_VERSION=" "" MRS_SDK_QT_VERSION "${_mrs_sdk_qt_version_line}")

# Resolve MRS_SDK_QT_ROOT from environment.
if(NOT DEFINED ENV{MRS_SDK_QT_ROOT})
    message(FATAL_ERROR "MRS_SDK_QT_ROOT is not set. Export it in your shell profile (e.g., export MRS_SDK_QT_ROOT=<path>).")
endif()
set(MRS_SDK_QT_ROOT "$ENV{MRS_SDK_QT_ROOT}")

# Validate that the SDK version is installed.
set(_mrs_sdk_qt_version_dir "${MRS_SDK_QT_ROOT}/${MRS_SDK_QT_VERSION}")
if(NOT EXISTS "${_mrs_sdk_qt_version_dir}")
    message(FATAL_ERROR "MRS SDK version ${MRS_SDK_QT_VERSION} is not installed. Expected at ${_mrs_sdk_qt_version_dir}")
endif()

message(NOTICE "MRS SDK root: ${MRS_SDK_QT_ROOT}")
message(NOTICE "MRS SDK version: ${MRS_SDK_QT_VERSION}")

# Include the SDK configuration.
include("${_mrs_sdk_qt_version_dir}/lib/cmake/mrs-sdk-qt/config.cmake")
