# MRS SDK Qt - Toolchain wrapper
# Generated by: mrs-sdk-manager use {{.Version}}
#
# This file resolves the SDK toolchain from the pinned version.
# Set CMAKE_TOOLCHAIN_FILE to this file in your Qt Creator kit or CMake invocation.
# The kit must also set MRS_SDK_QT_TOOLCHAIN_ID (e.g., desktop-qt6, yocto-qt5).

message(NOTICE "Configuring MRS SDK toolchain...")

# Ensure MRS_SDK_QT_TOOLCHAIN_ID is forwarded to try_compile() invocations
# (e.g., compiler ABI detection), where -D cache variables from the original
# command line are not automatically available.
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES MRS_SDK_QT_TOOLCHAIN_ID)

# Read the pinned SDK version.
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/version.conf" _mrs_sdk_qt_version_line REGEX "^MRS_SDK_QT_VERSION=")
string(REGEX REPLACE "^MRS_SDK_QT_VERSION=" "" MRS_SDK_QT_VERSION "${_mrs_sdk_qt_version_line}")

# Resolve MRS_SDK_QT_ROOT from environment.
if(NOT DEFINED ENV{MRS_SDK_QT_ROOT})
    message(FATAL_ERROR "MRS_SDK_QT_ROOT is not set. Export it in your shell profile (e.g., export MRS_SDK_QT_ROOT=<path>).")
endif()
set(MRS_SDK_QT_ROOT "$ENV{MRS_SDK_QT_ROOT}")

# Validate that the toolchain ID is set.
if(NOT DEFINED MRS_SDK_QT_TOOLCHAIN_ID)
    message(FATAL_ERROR "MRS_SDK_QT_TOOLCHAIN_ID is not set. Configure it in your Qt Creator kit (e.g., desktop-qt6, yocto-qt5).")
endif()

# Include the real toolchain from the pinned SDK version.
set(_mrs_sdk_qt_toolchain_path "${MRS_SDK_QT_ROOT}/${MRS_SDK_QT_VERSION}/lib/cmake/mrs-sdk-qt/toolchains/${MRS_SDK_QT_TOOLCHAIN_ID}.cmake")
if(NOT EXISTS "${_mrs_sdk_qt_toolchain_path}")
    message(FATAL_ERROR "Toolchain not found: ${_mrs_sdk_qt_toolchain_path}")
endif()
include("${_mrs_sdk_qt_toolchain_path}")

message(NOTICE "MRS SDK toolchain configuration complete.")
