# List tools recipes
default:
    @just --list

# You may have to do some manual setup to get the Go bin directory in your path for using mrs-sdk-manager.
# Here is a basic sample BASH command to add to your .bashrc:
# [[ -n "$(go env GOPATH)" ]] && PATH="$(go env GOPATH)/bin:$PATH"
# Install SDK tools
install:
    go -C mrs-sdk-manager install
