# List docs recipes
default:
    @JUST_LIST_HEADING="" just --list --list-prefix "    docs/"

# Install the docs dependencies
deps:
    npm i --no-fund --no-save

# Build the docs site
build:
    npm run build

# Run docs locally at http://localhost:4321
dev:
    npm run dev
